name: Apptainer Run

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches-ignore: []
  schedule:
    - cron: '0 0 * * SUN'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python: [3.8, 3.9, '3.10']
      fail-fast: false


    steps:

    - name: precleanup
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    - name: install graphviz
      run: |
        sudo apt-get install -y graphviz
        sudo curl -s https://raw.githubusercontent.com/apptainer/apptainer/main/tools/install-unprivileged.sh | bash -s - /usr/bin

    - name: checkout git repo
      uses: actions/checkout@v3

    - name: Set up Python 3.X
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        pip install .[testing]

    - name: install package itself
      run: |
         pip install .

    - name: testing
      run: |
        sequana_bioconvert --input-directory data/ --input-ext "fastq.gz" --output-ext "fasta.gz" --use-apptainer --command fastq2fasta --input-pattern "*" && cd bioconvert && sh bioconvert.sh



